### ISSUE TITLE
Changing a column definition (type/length) or adding a column should mark data dirty / enable SAVE button

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/sas-hot-editor#5]
Currently the SAVE button is only enabled when data is changed - same should happen when the table def is changed

**Comment by bojan88** [comment]
We need different API for this. Definition sent to SAS is extracted from data. It's created in adapter using Table object that we are trying to deprecate for some time.
When you change table def on front end, it's affecting the handsontable structure, and not changing data, so there's nothing to save.
We can change SAS service to accept new object for definition.

**Comment by boomskats** [comment]
Ok this is sorted now. 

The other issue you mention in #4  is separate issue that your comment is more relevant to, and you're right, it'll require a method to override the default behaviour of `Tables.add()`, which currently passes the minimum required column length for any given column. Being able to preserve column length even when a table has trailing blanks is important if we're going to give SAS users the ability to update the width of a given column, as this really should affect the width of the column of the table created by SAS at the backend rather than just the frontend validation. 

However this particular issue is fixed as it is fixed as of 8e7237ae17120eb52295415fa47169a7733581cf so closing this.
